user1 = User.create!(email: "user1@user.com", password:"abc123", name: "Bob", admin: true)
user2 = User.create!(email: "user2@user.com", password:"abc123", name: "Joe",admin: false)
user3 = User.create!(email: "user3@user.com", password:"abc123", name: "John",admin: false)
user4 = User.create!(email: "user4@user.com", password:"abc123", name: "Pit",admin: false)
user5 = User.create!(email: "user5@user.com", password:"abc123", name: "Smith",admin: false)
